# Generated by Django 3.2 on 2023-08-04 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_price_product_unti_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='unti_price',
            new_name='unit_price',
        ),
    ]
